#
###################################
# Site wide configuration
####################################
#
title: nick11roberts
email: n3robert@ucsd.edu
description: Drop me an email at n3robert@ucsd.edu.
url: https://nick11roberts.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Deep Learning", "Machine learning", "Python", "Data Science"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          United States/California
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Nick Roberts
  avatar: avatar.png
  job: "Student"
  bio: "<b>UC San Diego</b> senior in <b>Computer Science</b>.<br/><b>ML researcher</b> in <b>The Cottrell Lab</b>."
  ext-bio: "Senior at UC San Diego pursuing a Bachelor's Degree in Computer Science. <br/>Undergraduate machine learning researcher in The Cottrell Lab."
  email: n3robert@ucsd.edu
  disqus-shortname:
  twitter: NikolaiRoberts
  facebook: nick11roberts
  google:
    plus: #username
    analytics: UA-53407536-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nick11roberts #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: nick11roberts #username
  xing: #username
  instagram: n1cn11c
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: antielectron
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
