#
###################################
# Site wide configuration
####################################
#
title: Nicholas Roberts
email: nicholas11roberts@gmail.com
description: Drop me an email at nicholas11roberts@gmail.com
url: https://nick11roberts.science # the base hostname & protocol for your site
keywords: ["Foundation Models", "Deep Learning", "Machine Learning", "Large Language Models", "AI for Science"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          United States/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji



kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Nicholas Roberts"
  avatar: avatar.png
  job: "Postdoctoral Research Fellow (incoming)"
  bio: "Princeton Language and Intelligence <br/>Princeton University"
  ext-bio: "Princeton Language and Intelligence <br/>Princeton University"
  email: nick11roberts@cs.wisc.edu
  disqus-shortname:
  twitter: nick11roberts
  facebook: #nick11roberts
  google:
    plus: #username
    analytics: UA-53407536-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nick11roberts #username
  bluesky: nick11roberts.bsky.social
  stackoverflow: #123456/username   from a "https://stackoverflow.com/users/123456/username" link
  linkedin: #nick11roberts
  xing: #username
  instagram: #nick11roberts
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #antielectron
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
